package com.mopicmp.npcstudio.client.workspace;

import net.minecraft.resources.Identifier;

/**
 * Where each icon sits on the sheet.
 *
 * Generated by {@code tools/make-icons} — do not edit by hand; the next
 * run will write over it. Add a name to that tool's list instead.
 *
 * The artwork is Lucide, under the ISC licence, whose notice travels with
 * the sheet in {@code textures/gui/icons.txt}.
 */
public enum Icon {

	MENU(0, 0),
	COLLAPSE(1, 0),
	EXPAND(2, 0),
	MAXIMIZE(3, 0),
	RESTORE(4, 0),
	CLOSE(5, 0),
	DOCK(6, 0),
	PANELS(7, 0),
	RESET(0, 1),
	PLAYER_ON(1, 1),
	PLAYER_OFF(2, 1),
	VIEWPORT(3, 1),
	SCENE(4, 1),
	ASSETS(5, 1),
	CHARACTER(6, 1),
	ANIMATION(7, 1),
	WARDROBE(0, 2),
	BODY(1, 2),
	ENVIRONMENT(2, 2),
	GRAPH(3, 2),
	TIMELINE(4, 2),
	CAMERA(5, 2),
	MUSIC(6, 2),
	CAPTIONS(7, 2),
	BARE(0, 3),
	SAVE(1, 3),
	FILE(2, 3),
	IMAGE(3, 3),
	PLAY(4, 3),
	PAUSE(5, 3),
	REWIND(6, 3),
	DIALOGUE(7, 3),
	SETTINGS(0, 4),
	DRAFTS(1, 4),
	BROWSE(2, 4),
	ADD(3, 4),
	REMOVE(4, 4),
	CREDITS(5, 4),
	SEARCH(6, 4),
	CHECK(7, 4),
	CANCEL(0, 5),
	MAIN_HAND(1, 5),
	OFF_HAND(2, 5),
	MORNING(3, 5),
	NOON(2, 2),
	SUNSET(4, 5),
	NIGHT(5, 5),
	RAIN(6, 5),
	CLEAR(2, 2),
	FOCUS(7, 5),
	START(0, 6),
	SPOT(1, 6),
	MOVE_TOOL(2, 6),
	TURN_TOOL(3, 6),
	BRING_HERE(4, 6),
	POSE(5, 6),
	BENCH(6, 6),
	SHADERS(7, 6),
	EYES(1, 1),
	SCALE(0, 7),
	COPY(1, 7),
	FOLDER(2, 7),
	TOOL_MOVE(3, 7),
	TOOL_ROTATE(3, 6),
	TOOL_SCALE(4, 7),
	HANDLES(2, 6),
	SOLID(5, 7),
	CLOSED(6, 7),
	SERVER(7, 7),
	CONSOLE(0, 8),
	POWER(1, 8),
	STOP(2, 8),
	ADDRESS(3, 8),
	WARNING(4, 8),
	SEND(5, 8);

	public static final Identifier SHEET =
		com.mopicmp.npcstudio.NpcStudio.id("textures/gui/icons.png");

	/** One cell, and the size an icon is drawn at. */
	public static final int SIZE = 16;

	public static final int SHEET_WIDTH = 128;
	public static final int SHEET_HEIGHT = 144;

	public final int u;
	public final int v;

	Icon(int column, int row) {
		this.u = column * SIZE;
		this.v = row * SIZE;
	}

	/**
	 * Draws the icon, tinted.
	 *
	 * The sheet is white, so the tint is the colour: one drawing serves the
	 * dimmed state, the lit state and the accent without three copies of it
	 * on the sheet.
	 */
	public void draw(net.minecraft.client.gui.GuiGraphicsExtractor graphics,
			int x, int y, int colour) {
		graphics.blit(net.minecraft.client.renderer.RenderPipelines.GUI_TEXTURED, SHEET,
			x, y, u, v, SIZE, SIZE, SIZE, SIZE, SHEET_WIDTH, SHEET_HEIGHT, colour);
	}
}
